### ISSUE TITLE
Make frontmatter field names universal

### ISSUE THREAD

**Issue by kkomelin** [kkomelin/drupal_to_static#16]
Currently we name fields the following way:
```yaml
language: es
description: "This is meta description."
```
Let's make the names/structure universal to support other static site generators and plugins, such as [VuePress](https://vuepress.vuejs.org/guide/markdown.html#front-matter), [Octopress Multilingual](https://github.com/octopress/multilingual), etc.

New format:

```yaml
lang: es
meta:
  - name: description
    content: "This is meta description."
```
